aca_shop_home:
    path:     /
    defaults: { _controller: AcaShopBundle:Home:index }

aca_shop_login:
    path:     /login_user
    defaults: { _controller: AcaShopBundle:Home:login}


aca_shop_logout:
    path:     /logout
    defaults: { _controller: AcaShopBundle:Home:logout}


aca_shop_about:
    path:     /about
    defaults: { _controller: AcaShopBundle:About:about }

contact:
    path:     /contact
    defaults: { _controller: AcaShopBundle:Contact:contact }

products:
    path:     /products
    defaults: { _controller: AcaShopBundle:Products:show }

add:
    path:     /add_cart
    defaults: { _controller: AcaShopBundle:Cart:add }

display_cart:
   path:     /cart
   defaults: { _controller: AcaShopBundle:Cart:show }

delete_cart_item:
    path:     /delete_cart_item
    defaults: { _controller: AcaShopBundle:Cart:delete }

update_cart_item:
    path:     /update_cart_item
    defaults: { _controller: AcaShopBundle:Cart:update }

shipping_address:
    path: /shipping_address
    defaults: { _controller: AcaShopBundle:Cart:shippingAddress }

aca_place_order:
    path: /place_order
    defaults: { _controller: AcaShopBundle:Order:place }

aca_receipt:
    path: /receipt
    defaults: { _controller: AcaShopBundle:Receipt:show }